name: ZAP Scan

on: [push]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP baseline scan
        run: docker run -t owasp/zap2docker-stable zap-baseline.py -t http://testphp.vulnweb.com/
